a=int(input("enter the value of a"))
b=int(input("enter the value of b")) 
c=int(input("enter the value of c")) 
if (a<b and a<c):print("a is the smallest") 
if (b<a and b<c):print("b is the smallest")  
if (c<a and c<b):print("c is the smallest")                   